name: Nightly

on:
    schedule:
        - cron: "0 0 * * *"
    workflow_dispatch:

jobs:
    Create-Tasks-Summary:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  ref: dev/raging-echos

            - run: sh ./run_trailblazer_compare.sh >> $GITHUB_STEP_SUMMARY
